# Config active uniquement quand le profil "dev" est activé

# Afficher les requêtes SQL générées par Hibernate (utile pour comprendre/déboguer)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs détaillés en développement
logging.level.org.hibernate.SQL=DEBUG
logging.level.tn.esprit.autoloc=DEBUG
